Add validation matrix for linux, macos, windows over python versions (#4)
* Update validate-main.yaml
* Update qdox.py
* Update index.html
* Update pyproject.toml

diff --git a/.github/workflows/validate-main.yaml b/.github/workflows/validate-main.yaml
--- a/.github/workflows/validate-main.yaml
+++ b/.github/workflows/validate-main.yaml
@@ -7,18 +7,27 @@ on:
     branches: [main]
 
 jobs:
-  validate:
-    runs-on: ubuntu-latest
+
+  validate-matrix-linux:
+    strategy:
+      matrix:
+        os-version: [ubuntu-22.04, ubuntu-24.04]
+        python-version: [3.11, 3.12]
+
+    runs-on: ${{ matrix.os-version }}
+    continue-on-error: true
 
     steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
       with:
-        python-version: '3.11'
+        python-version: ${{ matrix.python-version }}
 
     - name: Lint
       run: |
-        python3 -m pip install --user pip --upgrade pylint
+        python3 -m venv .venv
+        source .venv/bin/activate
+        python3 -m pip install pip --upgrade pylint
         pylint qdox.py
 
     - name: Validate
@@ -26,4 +35,63 @@ jobs:
         python3 -m pip install .
         mv docs/index.html docs/validate.html
         python3 -m qdox --withcss
-        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
+        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr && false)
+
+  validate-matrix-macos:
+    strategy:
+      matrix:
+        os-version: [macos-13, macos-14, macos-15]
+        python-version: [3.11, 3.12]
+
+    runs-on: ${{ matrix.os-version }}
+    continue-on-error: true
+
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v5
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Lint
+      run: |
+        python3 -m venv .venv
+        source .venv/bin/activate
+        python3 -m pip install pip --upgrade pylint
+        pylint qdox.py
+
+    - name: Validate
+      run: |
+        python3 -m pip install .
+        mv docs/index.html docs/validate.html
+        python3 -m qdox --withcss
+        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr && false)
+
+  validate-matrix-windows:
+    strategy:
+      matrix:
+        os-version: [windows-2019, windows-2022]
+        python-version: [3.11, 3.12]
+
+    runs-on: ${{ matrix.os-version }}
+    continue-on-error: true
+
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v5
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Lint
+      run: |
+        python3 -m venv .venv
+        . .venv/scripts/activate
+        python3 -m pip install pip --upgrade pylint
+        pylint qdox.py
+
+    - name: Validate
+      run: |
+        python3 -m pip install .
+        mv docs/index.html docs/validate.html
+        python3 -m qdox --withcss
+        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr && false)
+
