Update validate-main.yaml

diff --git a/.github/workflows/validate-main.yaml b/.github/workflows/validate-main.yaml
--- a/.github/workflows/validate-main.yaml
+++ b/.github/workflows/validate-main.yaml
@@ -7,8 +7,9 @@ on:
     branches: [main]
 
 jobs:
-  validate-ubuntu-python3_11:
-    runs-on: ubuntu-latest
+
+  validate-ubuntu22_x64-python3_11:
+    runs-on: ubuntu-22.04
 
     steps:
     - uses: actions/checkout@v4
@@ -28,8 +29,8 @@ jobs:
         python3 -m qdox --withcss
         diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
 
-  validate-ubuntu-python3_12:
-    runs-on: ubuntu-latest
+  validate-ubuntu22_x64-python3_12:
+    runs-on: ubuntu-22.04
 
     steps:
     - uses: actions/checkout@v4
@@ -49,8 +50,50 @@ jobs:
         python3 -m qdox --withcss
         diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
 
-  validate-ubuntu-python3_13:
-    runs-on: ubuntu-latest
+  validate-ubuntu24_x64-python3_11:
+    runs-on: ubuntu-24.04
+
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v5
+      with:
+        python-version: '3.11'
+
+    - name: Lint
+      run: |
+        python3 -m pip install --user pip --upgrade pylint
+        pylint qdox.py
+
+    - name: Validate
+      run: |
+        python3 -m pip install .
+        mv docs/index.html docs/validate.html
+        python3 -m qdox --withcss
+        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
+
+  validate-ubuntu24_x64-python3_12:
+    runs-on: ubuntu-24.04
+
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Lint
+      run: |
+        python3 -m pip install --user pip --upgrade pylint
+        pylint qdox.py
+
+    - name: Validate
+      run: |
+        python3 -m pip install .
+        mv docs/index.html docs/validate.html
+        python3 -m qdox --withcss
+        diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
+
+  validate-ubuntu24_x64-python3_13:
+    runs-on: ubuntu-24.04
 
     steps:
     - uses: actions/checkout@v4
@@ -69,3 +112,4 @@ jobs:
         mv docs/index.html docs/validate.html
         python3 -m qdox --withcss
         diff docs/index.html docs/validate.html || (echo '***ERROR***: Did you forget to run `make` before pushing your latest changes?' >/dev/stderr;false)
+
